---
services:
  bot:
    tty: true
    build:
      context: .
      args:
        APP_USER: ${APP_USER:-twitchbot}
        APP_UID: ${APP_UID:-10123}
        APP_GID: ${APP_GID:-10123}
    env_file: .env
    user: "${APP_UID:-10123}:${APP_GID:-10123}"
    command: ["watch"]
    restart: unless-stopped
    volumes:
      - bot-data:/app/var:rw
      - ./src/:/app/src:rw
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHONUNBUFFERED: "1"

    stop_grace_period: 20s
    logging:
      driver: local
      options:
        max-size: "3m"
        max-file: "2"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
        reservations:
          cpus: "0.10"
          memory: 128M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "3m"
        max-file: "2"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

volumes:
  bot-data:
