services:
  bot:
    tty: true
    build: .
    env_file: .env
    command: [ "watch" ]
    volumes:
      - ./var/:/app/var:rw
      - ./src/:/app/src:rw
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    stop_grace_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
