---
services:
  bot:
    tty: true
    build: .
    env_file: .env
    command: ["watch"]
    restart: unless-stopped
    volumes:
      - ./var/:/app/var:rw
      - ./src/:/app/src:rw
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHONUNBUFFERED: "1"
    stop_grace_period: 20s
    logging:
      driver: local
      options:
        max-size: "3m"
        max-file: "2"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "3m"
        max-file: "2"
