name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: stage
    concurrency:
      group: deploy-prod
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to stage over SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          set -euxo pipefail
          PORT="${SSH_PORT:-22}"
          ssh -o StrictHostKeyChecking=no -p "$PORT" "$SSH_USER@$SSH_HOST" \
            'bash -euxo pipefail -c "cd /root/twitch-sub-bot && docker compose pull && docker compose down && docker compose up -d --build"'
